# Site settings
title: Grayscale
email: takimotouki@outlook.com
url: https://example.github.io
description: "Welcome to my home page.Here,you can find something about me and you can download something about Adobe.This is just a test page,so maybe I won't change it from now on. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: uki

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/takimoto_uki
  - title: Acfun
    url: http://www.acfun.cn/v/ac4230646
  - title: Bilibili
    url: http://space.bilibili.com/10812880
  - title: Baidu“newgame”bar
    url: https://tieba.baidu.com/f?kw=newgame&fr=ala0&loc=rec
  - title: github
    url: https://github.com/TakimotoUki

# Build settings
markdown: kramdown
permalink: pretty
