# Site settings
title: Grayscale
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/takimoto_uki
  - title: Acfun
    url: http://www.acfun.cn/v/ac4230646
  - title: Bilibili
    url: http://space.bilibili.com/10812880
  - title: Baidu“newgame”bar
    url: https://tieba.baidu.com/f?kw=newgame&fr=ala0&loc=rec
  - title: github
    url: https://github.com/TakimotoUki

# Build settings
markdown: kramdown
permalink: pretty
