# Site settings
title: Welcome to my page!
email: takimotouki@hotmail.com
description: "<center>欢迎来到我的个人主页</center><br /><center>在这里你能更加了解我，找到我的联系方式</center><br /><center>网页暂为测试用</center>"

# Color settings
color:
  primary-dark: '#412c1c'
  links: '#219ab3'

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/takimoto_uki
  - title: weibo
    url: https://weibo.com/takimotouki 
  - title: instagram
    url: https://www.instagram.com/takimotouki
  - title: tumblr
    url: https://www.tumblr.com/blog/takimotouki
  - title: github
    url: https://github.com/TakimotoUki

# Build settings
markdown: kramdown
permalink: pretty
